# Generated by Django 4.1.4 on 2023-11-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_profiles_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profiles',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
