# Generated by Django 4.1.4 on 2023-11-04 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_profiles_first_name_remove_profiles_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiles',
            old_name='name',
            new_name='user_name',
        ),
    ]
