# Generated by Django 4.1.4 on 2023-11-14 12:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_profiles_city_alter_profiles_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='data_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profiles',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
