# Generated by Django 4.1.4 on 2023-11-14 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_profiles_data_joined_profiles_website'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiles',
            old_name='data_joined',
            new_name='date_joined',
        ),
    ]
