# Generated by Django 4.1.4 on 2023-11-14 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0010_rename_data_joined_profiles_date_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=4000, null=True)),
                ('image_one', models.ImageField(blank=True, null=True, upload_to='images')),
                ('image_two', models.ImageField(blank=True, null=True, upload_to='images')),
                ('image_three', models.ImageField(blank=True, null=True, upload_to='images')),
                ('image_four', models.ImageField(blank=True, null=True, upload_to='images')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
