# Generated by Django 4.1.4 on 2023-11-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_skillcategory_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='website',
        ),
        migrations.AddField(
            model_name='about',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
