# Generated by Django 4.1.4 on 2023-11-17 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0020_alter_portfolio_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='image_four',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='image_one',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='image_three',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='image_two',
        ),
        migrations.CreateModel(
            name='PortfolioImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('portfolio', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(blank=True, max_length=1000, null=True)),
                ('course_description', models.TextField(blank=True, max_length=5000, null=True)),
                ('course_link', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
